[project]
name = "02baml"
version = "0.1.0"
description = "Testing BAML"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "baml-py>=0.206.1",
    "pydantic>=2.11.7",
    "requests>=2.32.5",
]
